# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sailw\Desktop\PR\PRPJ\test\genData.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_genData(object):
    def setupUi(self, genData):
        genData.setObjectName("genData")
        genData.resize(291, 376)
        self.layoutWidget = QtWidgets.QWidget(genData)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 23, 251, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioNormal = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioNormal.setChecked(True)
        self.radioNormal.setObjectName("radioNormal")
        self.verticalLayout.addWidget(self.radioNormal)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineMiu = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineMiu.setObjectName("lineMiu")
        self.horizontalLayout.addWidget(self.lineMiu)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineSigma = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineSigma.setObjectName("lineSigma")
        self.horizontalLayout.addWidget(self.lineSigma)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioUniform = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioUniform.setObjectName("radioUniform")
        self.verticalLayout_2.addWidget(self.radioUniform)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineA = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineA.setObjectName("lineA")
        self.horizontalLayout_2.addWidget(self.lineA)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineB = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineB.setObjectName("lineB")
        self.horizontalLayout_2.addWidget(self.lineB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.radioCustom = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioCustom.setObjectName("radioCustom")
        self.verticalLayout_3.addWidget(self.radioCustom)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.linePx = QtWidgets.QLineEdit(self.layoutWidget)
        self.linePx.setObjectName("linePx")
        self.horizontalLayout_3.addWidget(self.linePx)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineXa = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineXa.setObjectName("lineXa")
        self.horizontalLayout_4.addWidget(self.lineXa)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineXb = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineXb.setObjectName("lineXb")
        self.horizontalLayout_4.addWidget(self.lineXb)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineSize = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineSize.setObjectName("lineSize")
        self.horizontalLayout_5.addWidget(self.lineSize)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)

        self.retranslateUi(genData)
        self.buttonBox.accepted.connect(genData.accept)
        self.buttonBox.rejected.connect(genData.reject)
        QtCore.QMetaObject.connectSlotsByName(genData)

    def retranslateUi(self, genData):
        _translate = QtCore.QCoreApplication.translate
        genData.setWindowTitle(_translate("genData", "testGen"))
        self.radioNormal.setText(_translate("genData", "Normal"))
        self.label.setText(_translate("genData", "μ="))
        self.lineMiu.setText(_translate("genData", "0"))
        self.label_2.setText(_translate("genData", "σ="))
        self.lineSigma.setText(_translate("genData", "0.3"))
        self.radioUniform.setText(_translate("genData", "Uniform"))
        self.label_4.setText(_translate("genData", "a="))
        self.lineA.setText(_translate("genData", "-1"))
        self.label_3.setText(_translate("genData", "b="))
        self.lineB.setText(_translate("genData", "1"))
        self.radioCustom.setText(_translate("genData", "Custom"))
        self.label_5.setText(_translate("genData", "p(x)="))
        self.linePx.setText(_translate("genData", "exp(-x*x/2)/sqrt(2*π)"))
        self.label_6.setText(_translate("genData", "Range:"))
        self.lineXa.setText(_translate("genData", "-1"))
        self.label_7.setText(_translate("genData", "≤x＜"))
        self.lineXb.setText(_translate("genData", "1"))
        self.label_8.setText(_translate("genData", "Size:"))
        self.lineSize.setText(_translate("genData", "1000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    genData = QtWidgets.QDialog()
    ui = Ui_genData()
    ui.setupUi(genData)
    genData.show()
    sys.exit(app.exec_())

